### ISSUE TITLE
Add setting to change the value of the particles in the clientmods settings tab

### ISSUE THREAD

**Issue by src4026** [FlamingRCCars/CTF-Util#1]
I am opening this issue mostly for remembering to research about this. I would like to make this into a PR later. Furthermore, I also want to learn from this, so I would like if you don't do this yourself. >:)

Description: Add a setting in the client mods setting to change the value of the intensity of the particles.

**Comment by src4026** [comment]
> I am opening this issue mostly for remembering to research about this. I would like to make this into a PR later. I also want to learn from this, so I would like if you don't do this yourself. >:)

**Comment by Infernia829** [comment]
I wrote half of it before realizing you wanted to do it, anyways I'll save my code cause I want to see what you come up with, gl

**Comment by src4026** [comment]
> I wrote half of it before realizing you wanted to do it, anyways I'll save my code cause I want to see what you come up with, gl

Oh lol. It'll take time for me since I am not totally free for it. I'll have to plan my day out and see if I can manage today or tomorrow :D

**Comment by src4026** [comment]
Closing this Issue since I am not able to find time for it, and am busy. I don't want to disrupt your CSM's dev by keeping this issue open. Although I will be using your repository for future reference and I will be working on this locally for educational purposes :+1:

**Comment by Infernia829** [comment]
> Closing this Issue since I am not able to find time for it, and am busy. I don't want to disrupt your CSM's dev by keeping this issue open. Although I will be using your repository for future reference and I will be working on this locally for educational purposes 👍

Got you, I'll go ahead and merge my settings code
